### ISSUE TITLE
dubbing to persian(farsi)

### ISSUE THREAD

**Issue by bugbounted** [tanjimin/unsupervised-video-dubbing#2]
Hi [tanjimin](https://github.com/tanjimin),
how to make changes , for dubbing to persian(farsi) as destination language for dubbing.
if it's possible make new branch or new py file for persian edited version.
waiting for your commits
finest regards

**Comment by tanjimin** [comment]
Hi @elmirarokni , feel free to fork this repo and transfer it to persian. You could commit to here afterwards!
